/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace PtzCamera
{
    public sealed class DiscoveryResponse_t : LCM.LCM.LCMEncodable
    {
        public int totalCams;
        public String[] cameraNames;
 
        public DiscoveryResponse_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xeaadfb85578c0b7cL;
 
        static DiscoveryResponse_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("PtzCamera.DiscoveryResponse_t"))
                return 0L;
 
            classes.Add("PtzCamera.DiscoveryResponse_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.totalCams); 
 
            for (int a = 0; a < this.totalCams; a++) {
                __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.cameraNames[a]); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
            }
 
        }
 
        public DiscoveryResponse_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public DiscoveryResponse_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static PtzCamera.DiscoveryResponse_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            PtzCamera.DiscoveryResponse_t o = new PtzCamera.DiscoveryResponse_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.totalCams = ins.ReadInt32();
 
            this.cameraNames = new String[(int) totalCams];
            for (int a = 0; a < this.totalCams; a++) {
                __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.cameraNames[a] = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
            }
 
        }
 
        public PtzCamera.DiscoveryResponse_t Copy()
        {
            PtzCamera.DiscoveryResponse_t outobj = new PtzCamera.DiscoveryResponse_t();
            outobj.totalCams = this.totalCams;
 
            outobj.cameraNames = new String[(int) totalCams];
            for (int a = 0; a < this.totalCams; a++) {
                outobj.cameraNames[a] = this.cameraNames[a];
            }
 
            return outobj;
        }
    }
}

