/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace PtzCamera
{
    public sealed class PtzControlRequest_t : LCM.LCM.LCMEncodable
    {
        public String cameraName;
        public byte panValue;
        public byte tiltValue;
        public byte zoomValue;
 
        public PtzControlRequest_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xc7d1d3b50e3ac11cL;
 
        static PtzControlRequest_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("PtzCamera.PtzControlRequest_t"))
                return 0L;
 
            classes.Add("PtzCamera.PtzControlRequest_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.cameraName); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.panValue); 
 
            outs.Write(this.tiltValue); 
 
            outs.Write(this.zoomValue); 
 
        }
 
        public PtzControlRequest_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PtzControlRequest_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static PtzCamera.PtzControlRequest_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            PtzCamera.PtzControlRequest_t o = new PtzCamera.PtzControlRequest_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.cameraName = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.panValue = ins.ReadByte();
 
            this.tiltValue = ins.ReadByte();
 
            this.zoomValue = ins.ReadByte();
 
        }
 
        public PtzCamera.PtzControlRequest_t Copy()
        {
            PtzCamera.PtzControlRequest_t outobj = new PtzCamera.PtzControlRequest_t();
            outobj.cameraName = this.cameraName;
 
            outobj.panValue = this.panValue;
 
            outobj.tiltValue = this.tiltValue;
 
            outobj.zoomValue = this.zoomValue;
 
            return outobj;
        }
    }
}

